Jordans/models.py
from enum import unique
from os import name
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from datetime import datetime
import uuid
from sqlalchemy.orm import backref
from flask_wtf.recaptcha import fields
from werkzeug.security import generate_password_hash, check_password_hash
import secrets
from flask_login import LoginManager, UserMixin, login_manager

from flask_marshmallow import Marshmallow

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)



class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = False)
    token = db.Column(db.String, unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    drone = db.relationship('Jordan', backref= 'owner', lazy = True)

    def __init__(self,email, password,token= '', id='') -> None:
        self.id = self.set_id()
        self.email = email
        self.password = self.set_password(password)
        self.token = self.set_token(24)
        
    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self,password):
        self.pw_hash =generate_password_hash(password)
        return self.pw_hash

    def set_token(self,length):
        return secrets.token_hex(length)



class Jordan(db.Model):
    id = db.Column(db.String, primary_key= True)
    name = db.Column(db.String(150))
    description = db.Column(db.String(200), nullable = True)
    camera_quality = db.Column(db.Numeric(precision=10, scale= 2))
    flight_time = db.Column(db.String(100),nullable = True)
    max_speed = db.Column(db.String(100))
    dimensions = db.Column(db.String(100))
    weight = db.Column(db.String(50))
    cost_of_prod = db.Column(db.Numeric(precision=10,scale= 2))
    series = db.Column(db.String(150))
    user_token =db.Column(db.String, db.ForeignKey('user.token'), nullable = False)


    def __init__(self, name, description, camera_quality, flight_time, max_speed, dimensions, weight, cost_of_prod, series, user_token, id = ''):
        self.id = self.set_id()
        self.name = name
        self.description = description
        self.camera_quality = camera_quality
        self.flight_time = flight_time
        self.max_speed = max_speed
        self.dimensions = dimensions
        self.weight = weight
        self.cost_of_prod = cost_of_prod
        self.series = series
        self.user_token = user_token
    
    def set_id(self):
        return(secrets.token_urlsafe())

    # creating our marshaller to pull/create k,v pairs out of Drone attributes
class JordanSchema(ma.Schema):
        class Meta:
            # detailing fields(attributes) to be pulled out of our Drone class
            # instance(s) and sent to API call and vice-versa
            fields = ['id', 'name','description', 'camera_quality', 'flight_time', 'max_speed', 'dimensions', 'weight', 'cost_of_prod', 'series']

jordan_schema =JordanSchema()
jordans_schema = JordanSchema(many = True)

Jordans/forms.py
from flask_wtf import FlaskForm
from flask_wtf.recaptcha import validators
from wtforms import StringField, PasswordField,SubmitField
from wtforms.validators import DataRequired,  Email

class UserLoginForm(FlaskForm):
    # email, pw, submit, attributes 
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_button = SubmitField()

Jordans/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api
from flask_migrate import Migrate, migrate
from .models import db, login_manager,ma
from flask_cors import CORS



app = Flask(__name__)
app.config.from_object(Config)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
db.init_app(app)
login_manager.init_app(app)

ma.init_app(app)
login_manager.login_view = 'auth.signin'

migrate = Migrate(app,db)

CORS(app)

Jordans/api/routes.py
from os import name
from flask import Blueprint,request,jsonify
from Jordans.helpers import token_required
from Jordans.models import  Jordan, db, jordan_schema, jordans_schema

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {'some_value': 52, 'another_value': 'Coding Temple'}

@api.route('/jordans', methods = ['POST'])
@token_required
def create_jordan(current_user_token):
    name = request.json['name']
    description = request.json['description']
    camera_quality = request.json['camera_quality']
    flight_time = request.json['flight_time']
    max_speed = request.json['max_speed']
    dimensions = request.json['dimensions']
    weight = request.json['weight']
    cost_of_prod = request.json['cost_of_prod']
    series = request.json['series']    
    token = current_user_token.token 

    print(f'TEST: {current_user_token.token}')

    jordan = Jordan(name,description,camera_quality,flight_time,max_speed,dimensions, weight,cost_of_prod,series, user_token = token)

    db.session.add(jordan)
    db.session.commit()

    response = jordan_schema.dump(jordan)
    return jsonify(response)

@api.route('/jordans', methods = ['GET'])
@token_required
def get_shoes(current_user_token):
    owner = current_user_token.token
    jordans = Jordan.query.filter_by(user_token = owner).all()
    response = jordans_schema.dump(jordans)
    return jsonify(response)

@api.route('/jordans/<id>', methods = ['GET'])
@token_required
def get_shoe(current_user_token, id):
    jordan = Jordan.query.get(id)
    response = jordans_schema.dump(jordan)
    return jsonify(response)


@api.route('/jordans/<id>', methods = ['POST', 'PUT'])
@token_required
def update_shoe(current_user_token, id):
    jordan = Jordan.query.get(id)
    print (jordan)
    if jordan:
        jordan.name = request.json['name']
        jordan.description = request.json['description']

        db.session.commit()

        response = jordan_schema.dump(jordan)
        return jsonify(response)
    else:
        return jsonify({'Error': 'That Jordan does not exist!!!'})

@api.route('/jordans/<id>', methods = ['DELETE'])
@token_required
def delete_shoe(current_user_token, id):
    jordan = Jordan.querey.get(id)
    if jordan:
        db.session.delete(jordan)
        db.session.commit()

        return jsonify({'Success': f'shoe ID #{jordan.id} has been deleted)'})
    else:
        return jsonify({'Error': 'That shoe does not exist!'})

Jordans/authentication/routes.py
from flask import Blueprint, render_template, request,url_for, flash, redirect
from Jordans.forms import UserLoginForm
from Jordans.models import User, db, check_password_hash
from flask_login import login_user, login_required, logout_user


auth = Blueprint('auth',__name__,template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)
        new_user = User(email, password)
        db.session.add(new_user)
        db.session.commit()
        flash(f'You have successfully registered an account under{email}', 'user-created')
        return redirect(url_for('site.home'))
        


    return render_template('signup.html', form = form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)

        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You were successfully logged in')
            return redirect(url_for('site.home'))

        else:
            flash('Your Email/Password id incorrent')
            return redirect(url_for('auth.signin'))


    return render_template('signin.html', form = form)

@auth.route('/logout')
def logout():
    logout_user()
    flash('You have successfully logged out.')
    return redirect(url_for('site.home'))

Jordans/site/routes.py
from flask import Blueprint,render_template
from flask_login import login_required

site = Blueprint('site',__name__,template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')


@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

Jordans/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Air Jordan API</title>
</head>
<body>
    <nav class="ct-nav ">
        <div class="sticky-md-top">


            <div>
                <ul id="horizontal-list">
                    <a href="{{ url_for('site.home')}}">
                        <li>The Jordans Project</li>
                    </a>
                    <a href="">
                        <li>Donate</li>
                    </a>
                    {% if current_user.is_authenticated %}
                        
                    
                        <a href="{{ url_for('site.profile')}}">
                            <li>Profile</li>
                        </a>
                        <a href="{{url_for('auth.logout')}}">
                            <li>Log out</li>
                        </a>
                        
                    {% else %}
                        
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Create a Free Account</li>
                    </a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

{% endblock content %}
    <footer class="row" id="footer">
        <div class="col-2 md-2"></div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Buy</h4>
                        <p>Why Coding Drones </p>
                        <p>The Jordans Project</p>
                        <p>Donate</p>
                        <p>Spread the word</p>
                        <p>Our Success</p>
                    </div>
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Sell</h4>
                        <p>Fee Policy</p>
                        <p>How To Sell</p>
                    </div>    
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Support</h4>
                        <p>Contact US</p>
                        <p>FAQ's</p>
                        <p>Donate</p>
                        <p>Privacy</p>
                        <p>Cookies</p>
                    </div>
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>About US</h4>
                        <p>The Jordans Project</p>
                        <p>Careers</p>
                        <p>Donate</p>
                        <p>Spread the Word</p>
                        <p>Our Success</p>
                    </div>
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Forum</h4>
                        <p>Join The Chat</p>
                        <p>Stay up to date</p>
                    </div>
                </div>
        </div>
    </footer>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>